= Getting Started with Fedora/CentOS bootc

== Introduction

The Fedora/CentOS bootc project generates reference "base images" that
are designed for use with the https://github.com/containers/bootc[bootc project].

=== Container Images

- `quay.io/centos-bootc/centos-bootc:stream9` (CentOS Stream 9)

This is in development, see [Fedora bootc](https://gitlab.com/bootc-org/fedora-bootc/fedora-bootc-base) but as
of right now:

- ``
- `registry.gitlab.com/bootc-org/fedora-bootc/fedora-bootc-base/fedora-bootc-minimal:40`

=== Provisioning Philosophy

It is generally expected that you create a *custom* container image, derived from one of our base images
for deployment.

For more information on configuration, refer to the documentation for xref:producing-ign.adoc[Producing an Ignition File].

== Quickstart

=== Running as a container

include::getting-started-container.adoc[]

=== Booting on a local hypervisor

include::getting-started-local-virt.adoc[]

=== Booting on a cloud VM (AWS example)

include::getting-started-aws.adoc[]

=== Exploring the OS for the first time

By design, there are no hard-coded default credentials or non-root interactive users.

If you set up an xref:authentication.adoc[SSH key], you can SSH into the VM and explore the OS:

[source, bash]
----
ssh root@<ip address>
----

=== Key related projects

- https://github.com/containers/bootc[bootc]
- https://github.com/osbuild/bootc-image-builder[bootc-image-builder]
- https://gitlab.com/bootc-org/podman-bootc-cli[podman-bootc-cli]

Established key related and included projects:

- https://github.com/containers/podman[podman]
- https://systemd.io[systemd]

== Getting in touch

Bugs can be reported to:

- Fedora: <https://gitlab.com/bootc-org/fedora-bootc/fedora-bootc-base>
- CentOS: <https://github.com/CentOS/centos-bootc/>

For longer discussions related to Fedora bootc, use the https://discussion.fedoraproject.org/tag/bootc[forum].