= Configuring Storage

Fedora bootc is a container image that can be "materialized" into a disk image in 3 different ways:

- Anaconda (kickstart)
- bootc-image-builder
- `bootc install`

== Mounted Filesystems

Fedora bootc uses the bootc upstream project which currently uses ostree as a backend.  

For more on the filesystem layout, see https://containers.github.io/bootc/filesystem.html[bootc filesystem].

=== Version selection and bootup

Fedora bootc uses GRUB by default (except on s390x).  A menu entry is created for each version of Fedora bootc currently available on a system. This menu entry references an `ostree` deployment which consists of a Linux kernel, an initramfs and a hash linking to an `ostree` commit (passed via the `ostree=` kernel argument). During bootup, `ostree` will read this kernel argument to determine which deployment to use as the root filesystem. Each update or change to the system (package installation, addition of kernel arguments) creates a new deployment. This enables rolling back to a previous deployment if the update causes problems.
